In [11]:
import pandas as pd
import numpy as np
from scipy import optimize
from scipy import stats
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import  train_test_split
from sklearn.metrics import mean_absolute_error, SCORERS, mean_squared_error
from sklearn.linear_model import (LinearRegression, Ridge, Lasso,ElasticNet,
                                    LogisticRegression)
from sklearn.datasets import load_boston
data = load_boston()
from sklearn import model_selection
from sklearn import linear_model
from sklearn import preprocessing
%matplotlib inline
from sklearn import feature_selection
from sklearn import metrics

In [12]:
data.keys()

dict_keys(['data', 'target', 'feature_names', 'DESCR', 'filename'])

In [13]:
df = pd.DataFrame(data['data'], columns = data['feature_names'])

In [14]:
df['target'] = data['target']

In [15]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [16]:
df.dropna(inplace=True)

In [17]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  target  
0     15.3  396.90   4.98    24.0  
1     17.8  396.90   9.14    21.6  
2     17.8  392.83   4.03    34.7  
3     18.7  394.63   2.94    33.4  
4     18.7  396.90   5.33    36.2

In [18]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'target'],
      dtype='object')

In [19]:
df['RAD_PTRATIO'] = df['RAD']*df['PTRATIO']
df['RM_AGE'] = df['RM']*df['AGE']
df['DIS_NOX'] = df['DIS']*df['NOX']
df['RAD_TAX'] = df['RAD']*df['TAX']
df['LSTAT_PTRATIO'] = df['LSTAT']*df['PTRATIO']
df['ZN_INDUS'] = df['ZN']*df['INDUS']
df['RM_TAX'] = df['RM']*df['TAX']
df['AGE_PTRATIO'] = df['AGE']*df['PTRATIO']
df['CRIM_LSTAT'] = df['CRIM']*df['LSTAT']
df['CRIM_ZN'] = df['CRIM']*df['ZN']
df['CRIM_TAX'] = df['CRIM']*df['TAX']

df['CRIM_TAX_CRIM_ZN'] = df['CRIM_TAX']*df['CRIM_ZN']
df['RM_TAX_ZN_INDUS'] = df['RM_TAX']*df['ZN_INDUS']
df['ZN_INDUS_DIS_NOX'] = df['ZN_INDUS']*df['DIS_NOX']
df['CRIM_LSTAT_DIS_NOX'] = df['CRIM_LSTAT']*df['DIS_NOX']
df['CRIM_ZN_DIS_NOX'] = df['CRIM_ZN']*df['DIS_NOX']
df['RAD_PTRATIO_RAD_TAX'] = df['RAD_PTRATIO']*df['RAD_TAX']
df['LSTAT_PTRATIO_RAD_TAX'] = df['LSTAT_PTRATIO']*df['RAD_TAX']

df['ZN_INDUS_RAD_TAX'] = df['ZN_INDUS']*df['RAD_TAX']
df['CRIM_LSTAT_RAD_TAX'] = df['CRIM_LSTAT']*df['RAD_TAX']
df['CRIM_TAX_RAD_TAX'] = df['CRIM_TAX']*df['RAD_TAX']



In [20]:
df['RAD=PTRATIO'] = df['RAD']/df['PTRATIO']
df['RM=AGE'] = df['RM']/df['AGE']
df['DIS=NOX'] = df['DIS']/df['NOX']
df['RAD=TAX'] = df['RAD']/df['TAX']
df['LSTAT=PTRATIO'] = df['LSTAT']/df['PTRATIO']
df['RM=TAX'] = df['RM']/df['TAX']
df['AGE=PTRATIO'] = df['AGE']/df['PTRATIO']
df['CRIM=LSTAT'] = df['CRIM']/df['LSTAT']
df['CRIM=TAX'] = df['CRIM']/df['TAX']

df['ZN_INDUS+DIS_NOX'] = df['ZN_INDUS']/df['DIS_NOX']
df['CRIM_LSTAT+DIS_NOX'] = df['CRIM_LSTAT']/df['DIS_NOX']
df['CRIM_ZN_DIS+NOX'] = df['CRIM_ZN']/df['DIS_NOX']
df['RAD_PTRATIO+RAD_TAX'] = df['RAD_PTRATIO']/df['RAD_TAX']
df['LSTAT_PTRATIO+RAD_TAX'] = df['LSTAT_PTRATIO']/df['RAD_TAX']

df['ZN_INDUS+RAD_TAX'] = df['ZN_INDUS']/df['RAD_TAX']
df['CRIM_LSTAT+RAD_TAX'] = df['CRIM_LSTAT']/df['RAD_TAX']
df['CRIM_TAX+RAD_TAX'] = df['CRIM_TAX']/df['RAD_TAX']

In [21]:
df['RAD*PTRATIO'] = df['RAD']%df['PTRATIO']
df['RM*AGE'] = df['RM']%df['AGE']
df['DIS*NOX'] = df['DIS']%df['NOX']
df['RAD*TAX'] = df['RAD']%df['TAX']
df['LSTAT*PTRATIO'] = df['LSTAT']%df['PTRATIO']
df['RM*TAX'] = df['RM']%df['TAX']
df['AGE*PTRATIO'] = df['AGE']%df['PTRATIO']
df['CRIM*LSTAT'] = df['CRIM']%df['LSTAT']
df['CRIM*TAX'] = df['CRIM']%df['TAX']

df['ZN_INDUS*DIS_NOX'] = df['ZN_INDUS']%df['DIS_NOX']
df['CRIM_LSTAT*DIS_NOX'] = df['CRIM_LSTAT']%df['DIS_NOX']
df['CRIM_ZN_DIS*NOX'] = df['CRIM_ZN']%df['DIS_NOX']
df['RAD_PTRATIO*RAD_TAX'] = df['RAD_PTRATIO']%df['RAD_TAX']
df['LSTAT_PTRATIO*RAD_TAX'] = df['LSTAT_PTRATIO']%df['RAD_TAX']

df['ZN_INDUS*RAD_TAX'] = df['ZN_INDUS']%df['RAD_TAX']
df['CRIM_LSTAT*RAD_TAX'] = df['CRIM_LSTAT']%df['RAD_TAX']
df['CRIM_TAX*RAD_TAX'] = df['CRIM_TAX']%df['RAD_TAX']

In [22]:
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  ...  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0  ...   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0  ...   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0  ...   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0  ...   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0  ...   

   CRIM*LSTAT  CRIM*TAX  ZN_INDUS*DIS_NOX  CRIM_LSTAT*DIS_NOX  \
0     0.00632   0.00632           1.97244            0.031474   
1     0.02731   0.02731           0.00000            0.249613   
2     0.02729   0.02729           0.00000            0.109979   
3     0.03237   0.03237           0.00000            0.095168   
4     0.06905   0.06905           0.00000            0.368036   

   CRIM_ZN_DIS*NOX  RAD_PTRATIO*RAD_TAX  LSTAT_PTRATIO*RAD_TAX  \
0          0.11376                 15.3                 76.194   
1          0.00000                 35.6                162.692   
2          0.00000                 35.6                 71.734   
3          0.00000                 56.1                 54.978   
4          0.00000                 56.1                 99.671   

   ZN_INDUS*RAD_TAX  CRIM_LSTAT*RAD_TAX  CRIM_TAX*RAD_TAX  
0             41.58            0.031474           1.87072  
1              0.00            0.249613           6.60902  
2              0.00            0.109979           6.60418  
3              0.00            0.095168           7.18614  
4              0.00            0.368036          15.32910  

[5 rows x 69 columns]

In [23]:
df_train,df_test = train_test_split(df.copy(),test_size=0.15,random_state=17)

In [24]:
x_train = df_train.drop('target', axis = 1)
y_train = df_train['target']

In [25]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [26]:
x_test = df_test.drop('target',axis = 1)
y_test = df_test['target']

In [27]:
preds_train = lr.predict(x_train)
preds_test = lr.predict(x_test)

In [28]:
mse_train = mean_squared_error(preds_train, y_train)
mse_test = mean_squared_error(preds_test, y_test)

In [29]:
print('train_metric ', (mse_train)**(1/2))
print('test_metric ', (mse_test)**(1/2))


train_metric  3.1236017439468435
test_metric  2.6714077230157494


In [30]:
lasso = Lasso(alpha = 0.1)

In [31]:
lasso.fit(x_train, y_train)

C:\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 3774.05716381109, tolerance: 3.775355079069768
  model = cd_fast.enet_coordinate_descent(


Lasso(alpha=0.1)

In [32]:
lasso.coef_

array([-0.00000000e+00,  4.73780997e-02,  7.94764426e-03,  0.00000000e+00,
       -0.00000000e+00,  6.32073297e+00,  1.66926298e-01, -0.00000000e+00,
        0.00000000e+00,  1.01515922e-01, -2.27821363e-01,  4.91316521e-03,
       -9.23752768e-01, -5.21342755e-02,  1.87600583e-03, -2.23621955e+00,
       -1.84096453e-04,  3.87098683e-02,  3.36996558e-02, -1.92161433e-02,
       -1.17835113e-02,  1.86552179e-02, -0.00000000e+00, -2.34908604e-04,
       -1.45018066e-03,  1.70921474e-05, -4.93681189e-03,  1.27183851e-02,
        9.90194267e-02,  2.41418872e-06, -2.76539354e-06, -7.72447627e-06,
        1.83198194e-06, -7.59938763e-08,  0.00000000e+00,  0.00000000e+00,
       -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,  0.00000000e+00,
        0.00000000e+00,  7.84826440e+00, -0.00000000e+00, -2.02392330e-02,
        3.83402542e-02, -0.00000000e+00,  0.00000000e+00, -0.00000000e+00,
       -0.00000000e+00, -0.00000000e+00, -0.00000000e+00,  3.15949544e-01,
        2.10789554e-01,  

In [33]:
lasso.intercept_

-41.61982499935611

In [34]:
pd.DataFrame({'features':df_train.drop(['target'], axis = 1).columns,
             'coefs':lasso.coef_}).query('coefs!=0')

features         coefs
1                      ZN  4.737810e-02
2                   INDUS  7.947644e-03
5                      RM  6.320733e+00
6                     AGE  1.669263e-01
9                     TAX  1.015159e-01
10                PTRATIO -2.278214e-01
11                      B  4.913165e-03
12                  LSTAT -9.237528e-01
13            RAD_PTRATIO -5.213428e-02
14                 RM_AGE  1.876006e-03
15                DIS_NOX -2.236220e+00
16                RAD_TAX -1.840965e-04
17          LSTAT_PTRATIO  3.870987e-02
18               ZN_INDUS  3.369966e-02
19                 RM_TAX -1.921614e-02
20            AGE_PTRATIO -1.178351e-02
21             CRIM_LSTAT  1.865522e-02
23               CRIM_TAX -2.349086e-04
24       CRIM_TAX_CRIM_ZN -1.450181e-03
25        RM_TAX_ZN_INDUS  1.709215e-05
26       ZN_INDUS_DIS_NOX -4.936812e-03
27     CRIM_LSTAT_DIS_NOX  1.271839e-02
28        CRIM_ZN_DIS_NOX  9.901943e-02
29    RAD_PTRATIO_RAD_TAX  2.414189e-06
30  LSTAT_PTRATIO_RAD_TAX -2.765394e-06
31       ZN_INDUS_RAD_TAX -7.724476e-06
32     CRIM_LSTAT_RAD_TAX  1.831982e-06
33       CRIM_TAX_RAD_TAX -7.599388e-08
41             CRIM=LSTAT  7.848264e+00
43       ZN_INDUS+DIS_NOX -2.023923e-02
44     CRIM_LSTAT+DIS_NOX  3.834025e-02
51            RAD*PTRATIO  3.159495e-01
52                 RM*AGE  2.107896e-01
54                RAD*TAX  1.899078e-01
55          LSTAT*PTRATIO -1.971531e-02
56                 RM*TAX  6.219488e+00
57            AGE*PTRATIO -2.434595e-02
59               CRIM*TAX -2.669741e-01
63    RAD_PTRATIO*RAD_TAX  5.206843e-02
64  LSTAT_PTRATIO*RAD_TAX  4.948324e-03
65       ZN_INDUS*RAD_TAX -4.510205e-02
66     CRIM_LSTAT*RAD_TAX -6.297625e-02
67       CRIM_TAX*RAD_TAX -2.462478e-05

In [35]:
preds_train = lasso.predict(x_train)
preds_test = lasso.predict(x_test)

In [36]:
mse_train = mean_squared_error(preds_train, y_train)
mse_test = mean_squared_error(preds_test, y_test)

In [37]:
print('train_metric ', (mse_train)**(1/2))
print('test_metric ', (mse_test)**(1/2))

train_metric  3.5247095932518415
test_metric  2.9176706002134463


In [38]:
ridge = Ridge(alpha = 0.0001)

In [39]:
ridge.fit(x_train, y_train)

C:\anaconda3\lib\site-packages\sklearn\linear_model\_ridge.py:147: LinAlgWarning: Ill-conditioned matrix (rcond=2.28721e-23): result may not be accurate.
  return linalg.solve(A, Xy, sym_pos=True,


Ridge(alpha=0.0001)

In [40]:
ridge.coef_

array([-1.60077136e+00,  3.71767010e-02, -3.71748991e-02,  5.17021424e-01,
        2.99757770e+01,  7.81577857e+00, -1.66469883e+00,  3.20256076e+01,
       -1.33819174e+01,  1.03385299e-01, -4.90902384e-01,  5.66541994e-03,
        1.74731000e+01,  3.46699175e-01, -2.68919958e-02, -4.05685969e+01,
        6.43157379e-04, -4.75470035e-01, -2.94233397e-02, -1.97526799e-02,
        4.77335735e-02, -1.68758346e-01, -4.80084010e-01,  1.27973960e-02,
        3.70241191e-03,  2.37584481e-05,  3.60736317e-03,  1.03335402e-01,
        1.70916553e-01,  6.11144778e-06, -3.14143120e-06, -9.99549589e-06,
        9.43932753e-06, -6.34131541e-07,  2.28257954e+02, -2.84780013e+00,
       -6.71574179e+00, -1.83436790e+02, -1.55605428e+02,  8.18914331e+01,
        1.61998226e+01,  1.26238754e+01, -9.34758736e+00,  3.06747929e-02,
        1.21003352e-01, -1.24431036e+00,  8.54203164e+01, -9.77111426e+00,
        1.17341945e-01,  1.04960118e+02, -5.98923849e+00,  1.86604384e+00,
       -9.14167157e-02, -

In [41]:
ridge.intercept_

-71.75229336328053

In [42]:
pd.DataFrame({'features':df_train.drop(['target'], axis = 1).columns,
             'coefs':ridge.coef_}).query('coefs!=0')

features      coefs
0                    CRIM  -1.600771
1                      ZN   0.037177
2                   INDUS  -0.037175
3                    CHAS   0.517021
4                     NOX  29.975777
..                    ...        ...
63    RAD_PTRATIO*RAD_TAX   0.346858
64  LSTAT_PTRATIO*RAD_TAX  -0.000268
65       ZN_INDUS*RAD_TAX  -0.029460
66     CRIM_LSTAT*RAD_TAX  -0.168741
67       CRIM_TAX*RAD_TAX  -0.000146

[68 rows x 2 columns]

In [43]:
preds_train = ridge.predict(x_train)
preds_test = ridge.predict(x_test)

In [44]:
mse_train = mean_squared_error(preds_train, y_train)
mse_test = mean_squared_error(preds_test, y_test)

In [45]:
print('train_metric ', (mse_train)**(1/2))
print('test_metric ', (mse_test)**(1/2))

train_metric  3.1482089885660125
test_metric  2.602043030075893


In [46]:
el =ElasticNet(alpha = 0.001)

In [47]:
el.fit(x_train, y_train)

C:\anaconda3\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:529: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations. Duality gap: 2382.0197183386013, tolerance: 3.775355079069768
  model = cd_fast.enet_coordinate_descent(


ElasticNet(alpha=0.001)

In [48]:
el.coef_

array([-4.67429080e-01,  2.72622571e-02,  2.23945647e-02,  7.24513202e-01,
       -4.42993290e+00,  7.36749266e+00, -1.87172545e-01,  1.34407800e+00,
        5.72690875e-01,  1.00709985e-01, -1.32020934e-01,  6.26590906e-03,
       -7.92926251e-01, -6.20291037e-02, -3.10216338e-02, -5.10749475e+00,
        4.71879307e-04,  5.10751281e-02, -5.72886358e-03, -2.01125691e-02,
        2.30672032e-03,  2.41559277e-02, -9.53300706e-01,  9.15402143e-06,
        1.52096436e-03,  1.65840774e-05,  3.34228811e-03,  1.19006882e-02,
        2.87034733e-01,  1.78460426e-06, -2.72143586e-06, -6.37425632e-06,
        3.78196356e-07, -2.98390445e-08,  1.21922629e+00, -1.86519467e+00,
       -2.03980325e-01,  0.00000000e+00, -2.06159496e+00,  0.00000000e+00,
        5.11108469e+00,  1.43743345e+01,  0.00000000e+00,  1.87372544e-02,
        2.26874489e-02, -5.54796203e-02,  6.48719253e-01, -4.61057177e+00,
       -1.95713375e-01, -0.00000000e+00, -1.78349870e+00,  1.25670553e-01,
        1.79678163e-01,  

In [49]:
el.intercept_

-57.438235672523035

In [50]:
pd.DataFrame({'features':df_train.drop(['target'], axis = 1).columns,
             'coefs':ridge.coef_}).query('coefs!=0')

features      coefs
0                    CRIM  -1.600771
1                      ZN   0.037177
2                   INDUS  -0.037175
3                    CHAS   0.517021
4                     NOX  29.975777
..                    ...        ...
63    RAD_PTRATIO*RAD_TAX   0.346858
64  LSTAT_PTRATIO*RAD_TAX  -0.000268
65       ZN_INDUS*RAD_TAX  -0.029460
66     CRIM_LSTAT*RAD_TAX  -0.168741
67       CRIM_TAX*RAD_TAX  -0.000146

[68 rows x 2 columns]

In [51]:
preds_train = el.predict(x_train)
preds_test = el.predict(x_test)

In [52]:
mse_train = mean_squared_error(preds_train, y_train)
mse_test = mean_squared_error(preds_test, y_test)

In [53]:
print('train_metric ', (mse_train)**(1/2))
print('test_metric ', (mse_test)**(1/2))

train_metric  3.2848028463549306
test_metric  2.7908386774424523


In [54]:
y_test[2:3]

461    17.7
Name: target, dtype: float64

In [55]:
lr.predict(x_test[2:3])

array([17.54857286])